---
- name: Install from source
  become: false
  block:
    - name: Clone story repo
      git:
        repo: "https://github.com/piplabs/story"
        dest: "{{ user_dir }}/story"
        version: "{{ story_version }}"
        update: yes
        force: yes
        recursive: no

    - name: Insatll Story
      command: "{{ item }}"
      args:
        chdir: "{{ user_dir }}/story"
      with_items:
        - "go build -o story ./client"
        - "mv story /usr/local/bin/story"
      environment:
        PATH: "{{ path }}"
        GOPATH: "{{ user_dir }}/go"
